# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'middleman', '3.4.0'
gem 'middleman-livereload'
gem 'middleman-minify-html', :git => 'https://github.com/middleman/middleman-minify-html.git'
gem 'middleman-imageoptim'
gem 'middleman-favicon-maker'
gem 'middleman-autoprefixer'
gem "middleman-es6", github: "vast/middleman-es6"
gem "middleman-wagon", path: "./middleman-wagon"
gem 'susy'
gem 'compass'
gem 'modular-scale'
gem 'sitemap_generator'
gem 'puma'
gem 'rake'
gem 'builder'

group :darwin do
  gem 'rb-fsevent', require: false
end

group :linux do
  gem 'rb-inotify', require: false
end
